.TH GIT-ZPLY-REFRESH 1 "18 Oct 2014" "git-zply 0.1"
.SH NAME
git zply-refresh - Refresh patches in patch repo
.SH SYNOPSIS
.I git-zply-refresh
.B [-h] [-v] <patch-repo-dir> <since>
.SH DESCRIPTION
Generates a series of patches, syncs them into the patch repo, and then
commits them.
.SH OPTIONS
.SS -h
Print help
.SS -v
Print version to
.I stdout
.SH EXIT STATUS
0 on success
.P
1 on error
.SH BUGS
Report any bugs at
.I https://github.com/rconradharris/zply
.SH AUTHOR
Rick Harris <rconradharris@gmail.com>
.SH EXAMPLES
git zply-refresh ../patch-repo HEAD~10 # Refresh last 10 patches
.SH SEE ALSO
.B git-zply-refresh(1)
