.TH GIT-ZPLY-APPLY 1 "18 Oct 2014" "git-zply 0.1"
.SH NAME
git apply-patches - Apply patches from patch repo
.SH SYNOPSIS
.I git apply-patches
.B [-b <branch>] [-h] [-pP] [-r <patch-repo-dir> ] [-v]
.SH DESCRIPTION
Applies patches from patch repo to the working repo
.SH OPTIONS
.SS -b <branch>
Checkout out this branch in the working repo before applying
.SS -h
Print help
.SS -p
Pull upstream remote before applying patches. Overrides
I. ZPLY_UPSTREAM_PULL
environment variable.
.SS -P
Do not pull upstream remote before applying patches. Overrides
I. ZPLY_UPSTREAM_PULL
environment variable.
.SS -r <patch-repo-dir>
Patch repo directory path. Must supply this if ZPLY_PATCH_REPO_DIR is not set.
.SS -v
Print version to
.I stdout
.SH ENVIRONMENT
.SS ZPLY_PATCH_REPO_DIR
Patch repo directory path
.SS ZPLY_UPSTREAM_BRANCH
Name of upstream branch to pull before applying patches
.SS ZPLY_UPSTREAM_PULL
Whether to pull upstream before applying patches. '1' to pull, '0' to disable.
.SS ZPLY_UPSTREAM_REMOTE
Name of upstream remote to pull before applying patches
.SH EXIT STATUS
0 if patches applied cleanly
.P
1 if conflicts encountered
.P
2 on error
.SH BUGS
Report any bugs at
.I https://github.com/rconradharris/zply
.SH AUTHOR
Rick Harris <rconradharris@gmail.com>
.SH SEE ALSO
.B git-zply-diff(1), git-zply-fixup(1), git-zply-format(1), git-refresh-patches(1)
