.TH GIT-ZPLY-FORMAT 1 "18 Oct 2014" "git-zply 0.1"
.SH NAME
git zply-format - Prepare patches for adding to patch repo
.SH SYNOPSIS
.I git-zply-format
.B [-h] [-o <dir>] [-v] <file>
.SH DESCRIPTION
Strips out parts of a patch file which change frequently and would therefore
lead to "chatty-diffs" in the patch repo.
.SH OPTIONS
.SS -h
Print help
.SS -o <dir>
Use <dir> to store the resulting files, instead of the current working
directory.
.SS -v
Print version to
.I stdout
.SH EXIT STATUS
0 on success
.P
1 on error
.SH BUGS
Report any bugs at
.I https://github.com/rconradharris/zply
.SH AUTHOR
Rick Harris <rconradharris@gmail.com>
.SH SEE ALSO
.B git-zply-refresh(1)
