#!/usr/bin/env python
import os
import sys


def _remove_trailing_extra_blank_lines_from_subject(lines):
    """Different versions of git will output different amounts of trailing
    whitespace at the end of a subject headers, so we normalize it by only
    allowing a single trailing blank line.
    """
    for idx, line in enumerate(lines):
        if line.startswith('diff --git'):
            break
    else:
        return

    if idx < 2:
        return

    # If we have two blanks above first `diff --git` remove one of them
    if not lines[idx - 1].strip() and not lines[idx - 2].strip():
        del lines[idx - 1]


def _fixup(lines):
    # Delete From <hash> <magic-date> line
    del lines[0]

    # Delete git version
    del lines[-1]
    del lines[-1]
    del lines[-1]
    del lines[-1]

    _remove_trailing_extra_blank_lines_from_subject(lines)


def main():
    if len(sys.argv) < 2:
        print >> sys.stderr, "usage: git fixup-patch <filename>"
        return 2

    filename = sys.argv[1]

    if not os.path.exists(filename):
        print >> sys.stderr, "error: file '%s' not found"
        return 3


    with open(filename) as f:
        patch = f.read()

    lines = patch.split('\n')
    _fixup(lines)
    print '\n'.join(lines)
    return 0

if __name__ == '__main__':
    sys.exit(main())
