#!/bin/bash
#
# NAME
#
#   git-save-patch - save patch series to patch repo
#
# SYNOPSIS
#
#   git-save-patch <patch-repo-path> <since>
#
# DESCRIPTION
#
#   Creates a series of patches and saves them into the patch repo.
#
# OUTPUT
#
#   Prints current step to stdout
#
# EXIT STATUS
#
#   0 - success
#   1 - failure

function die() {
    >&2 echo $@
    exit 1
}

if [[ -z $1 ]] || [[ -z $2 ]]; then
    die "usage: git save-patch <patch-repo-path> <since>"
fi

PATCH_REPO_PATH=$1
SINCE=$2
PATCH_TMP_DIR=$PWD/.patches
BASED_ON_HASH=`git show --pretty="%H" $SINCE`

# TODO: Verify PATCH_REPO_PATH exists
# TODO: Verify PATCH_REPO_PATH is a git repository

# Create patch series
rm -rf $PATCH_TMP_DIR

echo "Formatting patches..."
git format-patch -kpo $PATCH_TMP_DIR $SINCE > /dev/null || die "git format-patch failed"

echo "Copying patches into patch repo..."
for patch in `ls $PATCH_TMP_DIR/*.patch`; do
    git fixup-patch $patch > $patch.tmp || die "git fixup-patch failed"
    mv $patch.tmp $patch

    # Only copy patches that meaningfully changed
    COPY_PATCH=1
    REPO_PATCH=$PATCH_REPO_PATH/`basename $patch`
    if [[ -e $REPO_PATCH ]]; then
        git diff-patch $patch $REPO_PATCH > /dev/null
        if [[ $? -eq 0 ]]; then
            COPY_PATCH=0
        elif [[ $? -ne 1 ]]; then
            die "git diff-patch failed"
        fi
    fi
    if [[ $COPY_PATCH -eq 1 ]]; then
        cp $patch $PATCH_REPO_PATH
    fi
done

pushd $PATCH_REPO_PATH > /dev/null

# Clean up any vestigial patches
echo "Cleaning up vestigial patches..."
for patch in `ls *.patch`; do
    patch_basename=`basename $patch`
    if [[ ! -e $PATCH_TMP_DIR/$patch_basename ]]; then
        git rm $patch_basename
        if [[ $? -ne 0 ]]; then
            die "git rm failed"
        fi
    fi
done

# Commit
echo "Commiting patches..."
git add *.patch
cat > .tmp-commit-msg <<-EOF
Saving patches...

Based-On: $BASED_ON_HASH
EOF
# -t would abort the commit if the message was not edited; we don't want to
# require that in all cases, so using -eF instead
git commit -qeF .tmp-commit-msg
rm .tmp-commit-msg
popd > /dev/null
rm -rf $PATCH_TMP_DIR
echo "Done."
