#!/bin/bash
# Commit all patches to patch repo

function die() {
    >&2 echo $@
    exit 1
}

function realpath {
    echo $(cd $(dirname $1); pwd)/$(basename $1);
}

if [[ -z $1 ]]; then
    die "usage: git zply-commit <patch-repo-patch>"
fi

PATCH_REPO_PATH=`realpath $1`

pushd $PATCH_REPO_PATH > /dev/null
git add *.patch
cat > .tmp-commit-msg <<-EOF
Saving patches...
EOF

# Add based-on annotation
if [[ -n $BASED_ON_HASH ]]; then
    echo >> .tmp-commit-msg
    echo "Based-On: $BASED_ON_HASH" >> .tmp-commit-msg
fi

# -t would abort the commit if the message was not edited; we don't want to
# require that in all cases, so using -eF instead
git commit -qeF .tmp-commit-msg
rm .tmp-commit-msg
popd > /dev/null
echo "Commited patches"
